---
# tasks file for pre-k8s
- name: "Add Kubernetes repository and install gpg key (CentOS)"
  yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes
    gpgkey:
    - http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
    - http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
  when: ansible_distribution == "CentOS"

- name: install kubeadm kubectl kubelet
  yum:
    name: kubeadm
    state: present

- name: "Load br_netfilter kernel module"
  modprobe:
    name: br_netfilter
    state: present

- name: "Set bridge-nf-call-iptables"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: "Set ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: disable swap
  shell: swapoff -a && sed -ri 's/.*swap.*/#&/' /etc/fstab

- name: Disable SELinux
  selinux:
    state: disabled

- name: open firewalld port
  firewalld:
    port: 10250/tcp
    state: enabled
    permanent: yes
    immediate: yes
    offline: true

- name: enable kubelet.service
  service:
    name: kubelet
    enabled: true
    state: started
